### ISSUE TITLE
.netrc: note that file is used by clients other than just 'ftp': curl, wget (,others?)

### ISSUE THREAD

**Issue by salewski** [mmaraya/netkit-ftp#34]
It's well-known that various FTP clients can make use of the `~/.netrc` file, but perhaps less well-known that clients such as [curl](https://curl.haxx.se/) and [wget](https://www.gnu.org/software/wget/) can use the file not only for FTP but also for HTTP user auth. It would be nice to mention this in `netrc(1)`.

**Comment by mmaraya** [comment]
Thanks for the commit and pull request, this has been merged.

**Comment by salewski** [comment]
Great; thanks @mmaraya,
-Al
