### ISSUE TITLE
capture failure, return code ?

### ISSUE THREAD

**Issue by setop** [mmaraya/netkit-ftp#42]
Is there any way to capture failure in command execution, for example when `Login authentication failed` ?

Currently, the return code is "0" :(

**Comment by mmaraya** [comment]
That could be a feature request but may break compatibility with applications that have been built to work with this. I strongly suggest using a safe, modern FTP client instead.

**Comment by setop** [comment]
Thanks for your reply.

> a safe, modern FTP client

Any suggestion of a good candidate ?

Regards

**Comment by mmaraya** [comment]
> Any suggestion of a good candidate ?

Filezilla seems to be popular. lftp is another popular client, and it's command-line. I haven't reviewed the security of either one of these, though, so buyer beware.
